language: node_js
node_js:
  - "10"
script:
 - cd functions
 - npm install
 - npm run lint
 - npm run test
 - cd ..
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --only hosting --token "1/feiJca5bUZ6K8urRSgWCuJ6oeU2jDdlLxC1x9slCDn8"
branches:
  only:
    - master